### ISSUE TITLE
SEVERE: Exception while executing runnable at org.freeplane.view.swing.map.MainView.updateBorder(MainView.java:759)

### ISSUE THREAD

**Issue by metacoma** [metacoma/freeplane_plugin_grpc#1]
```
Jan 29, 2023 7:37:31 PM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@585063ea
java.lang.NullPointerException
        at org.freeplane.features.nodestyle.NodeStyleController.getBorderDashMatchesEdgeDash(NodeStyleController.java:286)
        at org.freeplane.features.nodestyle.NodeStyleController.getBorderDashMatchesEdgeDash(NodeStyleController.java:608)
        at org.freeplane.view.swing.map.MainView.updateBorder(MainView.java:759)
        at org.freeplane.view.swing.map.NodeView.update(NodeView.java:1468)
        at org.freeplane.view.swing.map.NodeView.nodeChanged(NodeView.java:963)
        at org.freeplane.features.map.NodeModel.fireNodeChanged(NodeModel.java:233)
        at org.freeplane.features.map.NodeModel.fireSingleNodeChanged(NodeModel.java:224)
        at org.freeplane.features.map.NodeModel.fireNodeChanged(NodeModel.java:216)
        at org.freeplane.features.map.MapController.fireNodeChanged(MapController.java:671)
        at org.freeplane.features.map.MapController.nodeRefresh(MapController.java:950)
        at org.freeplane.features.map.MapController.nodeRefresh(MapController.java:905)
        at org.freeplane.features.map.MapController.nodeRefresh(MapController.java:899)
        at org.freeplane.features.attribute.AttributeController.createAttributeTableModel(AttributeController.java:117)
        at org.freeplane.features.attribute.mindmapmode.MAttributeController.addAttribute(MAttributeController.java:574)
        at org.freeplane.plugin.grpc.GrpcRegistration$FreeplaneImpl.nodeAttributeAdd(GrpcRegistration.java:135)
        at org.freeplane.plugin.grpc.FreeplaneGrpc$MethodHandlers.invoke(FreeplaneGrpc.java:765)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:355)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:867)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
````

Steps to reproduce:

Run [pomodoro.rb](https://github.com/metacoma/freeplane_plugin_grpc/blob/ca8f667a0f373506c579762c92ffd954ca1827c7/grpc/ruby/pomodoro.rb) file several times.

The issue may be in the process when the Freeplane gRPC plugin creates new child nodes.
 https://github.com/metacoma/freeplane_plugin_grpc/blob/ca8f667a0f373506c579762c92ffd954ca1827c7/src/main/java/org/freeplane/plugin/grpc/GrpcRegistration.java#L84-L99

**Comment by metacoma** [comment]
fixed by upgrading to the new freeplane version 1.12.9 #9
