### ISSUE TITLE
BUG: MindmapToJSON sometimes fails

### ISSUE THREAD

**Issue by metacoma** [metacoma/freeplane_plugin_grpc#10]
```
GRPC_SERVER=127.0.0.1:50051
GRPC_ARGS="-plaintext -proto ./freeplane.proto -format json"
GRPC_CALL="grpcurl -plaintext -proto ./freeplane.proto -d @ ${GRPC_SERVER}"

MindMapToJson() {
    echo '{}' | ${GRPC_CALL} freeplane.Freeplane/MindMapToJSON
} 
MindMapToJson()
```

leads to the java trace

```
EVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@161af441
java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
	at java.base/java.io.StringReader.<init>(StringReader.java:51)
	at org.jsoup.parser.Parser.parse(Parser.java:107)
	at org.jsoup.Jsoup.parse(Jsoup.java:58)
	at org.freeplane.plugin.grpc.GrpcRegistration$FreeplaneImpl.bodyText(GrpcRegistration.java:460)
	at org.freeplane.plugin.grpc.GrpcRegistration$FreeplaneImpl.nodeWalk(GrpcRegistration.java:493)
	at org.freeplane.plugin.grpc.GrpcRegistration$FreeplaneImpl.nodeWalk(GrpcRegistration.java:476)
	at org.freeplane.plugin.grpc.GrpcRegistration$FreeplaneImpl.nodeWalk(GrpcRegistration.java:476)
	at org.freeplane.plugin.grpc.GrpcRegistration$FreeplaneImpl.nodeWalk(GrpcRegistration.java:476)
	at org.freeplane.plugin.grpc.GrpcRegistration$FreeplaneImpl.nodeWalk(GrpcRegistration.java:476)
	at org.freeplane.plugin.grpc.GrpcRegistration$FreeplaneImpl.nodeWalk(GrpcRegistration.java:476)
	at org.freeplane.plugin.grpc.GrpcRegistration$FreeplaneImpl.nodeWalk(GrpcRegistration.java:476)
	at org.freeplane.plugin.grpc.GrpcRegistration$FreeplaneImpl.nodeWalk(GrpcRegistration.java:476)
	at org.freeplane.plugin.grpc.GrpcRegistration$FreeplaneImpl.mindMapToJSON(GrpcRegistration.java:509)
	at org.freeplane.plugin.grpc.FreeplaneGrpc$MethodHandlers.invoke(FreeplaneGrpc.java:1008)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:355)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:867)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by metacoma** [comment]
Can't reproduce after 52897ab0410264cac41876ec53a724f6ed6545dc
