### ISSUE TITLE
MindMapFromJSON exception: java.lang.NullPointerException: Cannot invoke "java.util.Collection.iterator()" because "styleKeys" is null

### ISSUE THREAD

**Issue by metacoma** [metacoma/freeplane_plugin_grpc#8]
````
Jul 07, 2023 2:09:48 PM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@48633550
java.lang.NullPointerException: Cannot invoke "java.util.Collection.iterator()" because "styleKeys" is null
        at org.freeplane.features.icon.IconController$1.getProperty(IconController.java:102)
        at org.freeplane.features.icon.IconController$1.getProperty(IconController.java:98)
        at org.freeplane.features.mode.CombinedPropertyChain.getProperty(CombinedPropertyChain.java:48)
        at org.freeplane.features.icon.IconController.getIcons(IconController.java:131)
        at org.freeplane.view.swing.map.MainView.updateIcons(MainView.java:403)
        at org.freeplane.view.swing.map.NodeView.update(NodeView.java:1498)
        at org.freeplane.view.swing.map.NodeView.nodeChanged(NodeView.java:963)
        at org.freeplane.features.map.NodeModel.fireNodeChanged(NodeModel.java:231)
        at org.freeplane.features.map.NodeModel.fireSingleNodeChanged(NodeModel.java:222)
        at org.freeplane.features.map.NodeModel.fireNodeChanged(NodeModel.java:214)
        at org.freeplane.features.map.MapController.fireNodeChanged(MapController.java:671)
        at org.freeplane.features.map.MapController.nodeRefresh(MapController.java:950)
        at org.freeplane.features.map.MapController.nodeRefresh(MapController.java:905)
        at org.freeplane.features.map.MapController.nodeRefresh(MapController.java:899)
        at org.freeplane.features.attribute.AttributeController.createAttributeTableModel(AttributeController.java:117)
        at org.freeplane.features.attribute.mindmapmode.MAttributeController.addAttribute(MAttributeController.java:574)
        at org.freeplane.plugin.grpc.GrpcRegistration$FreeplaneImpl.recursiveJSONLoop(GrpcRegistration.java:394)
        at org.freeplane.plugin.grpc.GrpcRegistration$FreeplaneImpl.recursiveJSONLoop(GrpcRegistration.java:387)
        at org.freeplane.plugin.grpc.GrpcRegistration$FreeplaneImpl.recursiveJSONLoop(GrpcRegistration.java:375)
        at org.freeplane.plugin.grpc.GrpcRegistration$FreeplaneImpl.recursiveJSONLoop(GrpcRegistration.java:387)
        at org.freeplane.plugin.grpc.GrpcRegistration$FreeplaneImpl.recursiveJSONLoop(GrpcRegistration.java:387)
        at org.freeplane.plugin.grpc.GrpcRegistration$FreeplaneImpl.mindMapFromJSON(GrpcRegistration.java:422)
        at org.freeplane.plugin.grpc.FreeplaneGrpc$MethodHandlers.invoke(FreeplaneGrpc.java:1004)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:355)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:867)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by metacoma** [comment]
fixed by upgrading to the new freeplane version 1.12.9 #9
